openapi: 3.0.0
info:
  title: Resume API
  description: API for recruiters to get resume details
  version: 1.0.0

servers:
  - url: https://mockserver.example.com/v1
    description: Mock Server

paths:
  /resumes:
    get:
      summary: Get resumes (optionally filter by name)
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string
          description: Filter resumes by name
      responses:
        '200':
          description: List of resumes or a single resume if filtered by name
          content:
            application/json:
              example:
                - id: 1
                  name: "John Doe"
                  skills: ["JavaScript", "Node.js"]
                - id: 2
                  name: "Jane Smith"
                  skills: ["Python", "Django"]
        '404':
          description: Resume not found
          content:
            application/json:
              example:
                error: "Resume not found for the given name"
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                error: "Internal server error"
